# Final Project #

## Create the DataFrame ##

In [1]:
import pandas as pd
import numpy as mp

In [2]:
# Create a reference to the CSV and import it into a Pandas DataFrame
csv_path = "Resources/student-por.csv"
students_df = pd.read_csv(csv_path)
students_df.head()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,4,0,11,11
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,2,9,11,11
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,6,12,13,12
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,0,14,14,14
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,0,11,13,13

In [3]:
students_address_df = students_df[students_df.address != 'R']
students_address_df.head()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,4,0,11,11
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,2,9,11,11
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,6,12,13,12
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,0,14,14,14
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,0,11,13,13

In [4]:
students_address_df.describe()

,age,Medu,Fedu,traveltime,studytime,failures,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
count,452.000000,452.000000,452.000000,452.00000,452.000000,452.000000,452.000000,452.000000,452.000000,452.000000,452.000000,452.000000,452.000000,452.000000,452.000000,452.000000
mean,16.723451,2.657080,2.409292,1.39823,1.964602,0.196903,3.909292,3.154867,3.196903,1.473451,2.269912,3.539823,3.884956,11.683628,11.867257,12.263274
std,1.213771,1.116146,1.095527,0.63581,0.820245,0.567946,0.966491,1.015576,1.164398,0.913900,1.281863,1.454623,4.903960,2.708187,2.779413,2.987658
min,15.000000,0.000000,0.000000,1.00000,1.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000
25%,16.000000,2.000000,2.000000,1.00000,1.000000,0.000000,4.000000,3.000000,2.000000,1.000000,1.000000,2.000000,0.000000,10.000000,10.000000,10.000000
50%,17.000000,3.000000,2.000000,1.00000,2.000000,0.000000,4.000000,3.000000,3.000000,1.000000,2.000000,4.000000,2.000000,12.000000,12.000000,12.000000
75%,18.000000,4.000000,3.000000,2.00000,2.000000,0.000000,5.000000,4.000000,4.000000,2.000000,3.000000,5.000000,6.000000,14.000000,14.000000,14.000000
max,22.000000,4.000000,4.000000,4.00000,4.000000,3.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,32.000000,19.000000,18.000000,19.000000

In [5]:
students_address_df.columns

Index(['school', 'sex', 'age', 'address', 'famsize', 'Pstatus', 'Medu', 'Fedu',
       'Mjob', 'Fjob', 'reason', 'guardian', 'traveltime', 'studytime',
       'failures', 'schoolsup', 'famsup', 'paid', 'activities', 'nursery',
       'higher', 'internet', 'romantic', 'famrel', 'freetime', 'goout', 'Dalc',
       'Walc', 'health', 'absences', 'G1', 'G2', 'G3'],
      dtype='object')

In [6]:
# Drop unrelated columns and Walc
students_address_df = students_address_df.drop(['school','G1', 'G2', 'G3', 'Walc'], axis=1)
students_address_df.head()

,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,reason,...,nursery,higher,internet,romantic,famrel,freetime,goout,Dalc,health,absences
0,F,18,U,GT3,A,4,4,at_home,teacher,course,...,yes,yes,no,no,4,3,4,1,3,4
1,F,17,U,GT3,T,1,1,at_home,other,course,...,no,yes,yes,no,5,3,3,1,3,2
2,F,15,U,LE3,T,1,1,at_home,other,other,...,yes,yes,yes,no,4,3,2,2,3,6
3,F,15,U,GT3,T,4,2,health,services,home,...,yes,yes,yes,yes,3,2,2,1,5,0
4,F,16,U,GT3,T,3,3,other,other,home,...,yes,yes,no,no,4,3,2,1,5,0

In [7]:
# perform get dummies on data set (less Walc) to binary encode for scaling
encoded_address_df = pd.get_dummies(students_address_df)
encoded_address_df.head()

,age,Medu,Fedu,traveltime,studytime,failures,famrel,freetime,goout,Dalc,...,activities_no,activities_yes,nursery_no,nursery_yes,higher_no,higher_yes,internet_no,internet_yes,romantic_no,romantic_yes
0,18,4,4,2,2,0,4,3,4,1,...,1,0,0,1,0,1,1,0,1,0
1,17,1,1,1,2,0,5,3,3,1,...,1,0,1,0,0,1,0,1,1,0
2,15,1,1,1,2,0,4,3,2,2,...,1,0,0,1,0,1,0,1,1,0
3,15,4,2,1,3,0,3,2,2,1,...,0,1,0,1,0,1,0,1,0,1
4,16,3,3,1,2,0,4,3,2,1,...,1,0,0,1,0,1,1,0,1,0

In [8]:
# keep encoded df clean from y data for prediction purposes
working_students_df = encoded_address_df.copy()
working_students_df.head()

,age,Medu,Fedu,traveltime,studytime,failures,famrel,freetime,goout,Dalc,...,activities_no,activities_yes,nursery_no,nursery_yes,higher_no,higher_yes,internet_no,internet_yes,romantic_no,romantic_yes
0,18,4,4,2,2,0,4,3,4,1,...,1,0,0,1,0,1,1,0,1,0
1,17,1,1,1,2,0,5,3,3,1,...,1,0,1,0,0,1,0,1,1,0
2,15,1,1,1,2,0,4,3,2,2,...,1,0,0,1,0,1,0,1,1,0
3,15,4,2,1,3,0,3,2,2,1,...,0,1,0,1,0,1,0,1,0,1
4,16,3,3,1,2,0,4,3,2,1,...,1,0,0,1,0,1,1,0,1,0

In [9]:
Dalc_col = working_students_df[['Dalc']]
new_df = working_students_df.drop(['Dalc'], axis=1)
new_df['Dalc'] = Dalc_col
new_df.head()

,age,Medu,Fedu,traveltime,studytime,failures,famrel,freetime,goout,health,...,activities_yes,nursery_no,nursery_yes,higher_no,higher_yes,internet_no,internet_yes,romantic_no,romantic_yes,Dalc
0,18,4,4,2,2,0,4,3,4,3,...,0,0,1,0,1,1,0,1,0,1
1,17,1,1,1,2,0,5,3,3,3,...,0,1,0,0,1,0,1,1,0,1
2,15,1,1,1,2,0,4,3,2,3,...,0,0,1,0,1,0,1,1,0,2
3,15,4,2,1,3,0,3,2,2,5,...,1,0,1,0,1,0,1,0,1,1
4,16,3,3,1,2,0,4,3,2,5,...,0,0,1,0,1,1,0,1,0,1

In [10]:
new_df.dtypes

age                  int64
Medu                 int64
Fedu                 int64
traveltime           int64
studytime            int64
failures             int64
famrel               int64
freetime             int64
goout                int64
health               int64
absences             int64
sex_F                uint8
sex_M                uint8
address_U            uint8
famsize_GT3          uint8
famsize_LE3          uint8
Pstatus_A            uint8
Pstatus_T            uint8
Mjob_at_home         uint8
Mjob_health          uint8
Mjob_other           uint8
Mjob_services        uint8
Mjob_teacher         uint8
Fjob_at_home         uint8
Fjob_health          uint8
Fjob_other           uint8
Fjob_services        uint8
Fjob_teacher         uint8
reason_course        uint8
reason_home          uint8
reason_other         uint8
reason_reputation    uint8
guardian_father      uint8
guardian_mother      uint8
guardian_other       uint8
schoolsup_no         uint8
schoolsup_yes        uint8
famsup_no            uint8
famsup_yes           uint8
paid_no              uint8
paid_yes             uint8
activities_no        uint8
activities_yes       uint8
nursery_no           uint8
nursery_yes          uint8
higher_no            uint8
higher_yes           uint8
internet_no          uint8
internet_yes         uint8
romantic_no          uint8
romantic_yes         uint8
Dalc                 int64
dtype: object

In [11]:
# Create the bins in which Drinking levels will be held
bins = [0,1,2,3,4,5]

# Create the names for the five bins
group_names = ["A.Not at all", "B.Slightly", "C.Moderately", "D.Very", "E.Extremely"]

In [12]:
# Create column to contain new bins
new_df["Likelyhood to Drink"] = pd.cut(new_df["Dalc"], bins, labels=group_names)
new_df = new_df.drop(['Dalc'], axis=1)

new_df

,age,Medu,Fedu,traveltime,studytime,failures,famrel,freetime,goout,health,...,activities_yes,nursery_no,nursery_yes,higher_no,higher_yes,internet_no,internet_yes,romantic_no,romantic_yes,Likelyhood to Drink
0,18,4,4,2,2,0,4,3,4,3,...,0,0,1,0,1,1,0,1,0,A.Not at all
1,17,1,1,1,2,0,5,3,3,3,...,0,1,0,0,1,0,1,1,0,A.Not at all
2,15,1,1,1,2,0,4,3,2,3,...,0,0,1,0,1,0,1,1,0,B.Slightly
3,15,4,2,1,3,0,3,2,2,5,...,1,0,1,0,1,0,1,0,1,A.Not at all
4,16,3,3,1,2,0,4,3,2,5,...,0,0,1,0,1,1,0,1,0,A.Not at all
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
638,17,2,3,2,2,0,4,4,3,3,...,1,0,1,0,1,0,1,1,0,A.Not at all
642,17,4,3,2,2,0,5,5,4,1,...,0,0,1,0,1,0,1,1,0,A.Not at all
645,18,3,1,1,2,0,4,3,4,1,...,0,0,1,0,1,0,1,1,0,A.Not at all
646,18,1,1,2,2,0,1,1,1,5,...,1,0,1,0,1,1,0,1,0,A.Not at all
647,17,3,1,2,1,0,2,4,5,2,...,0,1,0,0,1,0,1,1,0,C.Moderately

In [13]:
working_students_df.columns

Index(['age', 'Medu', 'Fedu', 'traveltime', 'studytime', 'failures', 'famrel',
       'freetime', 'goout', 'Dalc', 'health', 'absences', 'sex_F', 'sex_M',
       'address_U', 'famsize_GT3', 'famsize_LE3', 'Pstatus_A', 'Pstatus_T',
       'Mjob_at_home', 'Mjob_health', 'Mjob_other', 'Mjob_services',
       'Mjob_teacher', 'Fjob_at_home', 'Fjob_health', 'Fjob_other',
       'Fjob_services', 'Fjob_teacher', 'reason_course', 'reason_home',
       'reason_other', 'reason_reputation', 'guardian_father',
       'guardian_mother', 'guardian_other', 'schoolsup_no', 'schoolsup_yes',
       'famsup_no', 'famsup_yes', 'paid_no', 'paid_yes', 'activities_no',
       'activities_yes', 'nursery_no', 'nursery_yes', 'higher_no',
       'higher_yes', 'internet_no', 'internet_yes', 'romantic_no',
       'romantic_yes'],
      dtype='object')

In [14]:
# Reformat data (x-inputs, y labels)
data = new_df.values
X = data[:, 0:51]
y = data[:, 51]

y = y.reshape(-1, 1)
print(X)
print(y)

[[18 4 4 ... 0 1 0]
 [17 1 1 ... 1 1 0]
 [15 1 1 ... 1 1 0]
 ...
 [18 3 1 ... 1 1 0]
 [18 1 1 ... 0 1 0]
 [17 3 1 ... 1 1 0]]
[['A.Not at all']
 ['A.Not at all']
 ['B.Slightly']
 ['A.Not at all']
 ['A.Not at all']
 ['A.Not at all']
 ['A.Not at all']
 ['A.Not at all']
 ['A.Not at all']
 ['A.Not at all']
 ['A.Not at all']
 ['A.Not at all']
 ['A.Not at all']
 ['A.Not at all']
 ['A.Not at all']
 ['A.Not at all']
 ['A.Not at all']
 ['A.Not at all']
 ['B.Slightly']
 ['A.Not at all']
 ['A.Not at all']
 ['A.Not at all']
 ['A.Not at all']
 ['B.Slightly']
 ['A.Not at all']
 ['A.Not at all']
 ['B.Slightly']
 ['A.Not at all']
 ['E.Extremely']
 ['C.Moderately']
 ['A.Not at all']
 ['A.Not at all']
 ['A.Not at all']
 ['A.Not at all']
 ['A.Not at all']
 ['A.Not at all']
 ['B.Slightly']
 ['A.Not at all']
 ['A.Not at all']
 ['B.Slightly']
 ['A.Not at all']
 ['A.Not at all']
 ['A.Not at all']
 ['B.Slightly']
 ['A.Not at all']
 ['B.Slightly']
 ['A.Not at all']
 ['C.Moderately']
 ['B.Slightly']
 ['D.Very']
 ['A.Not at all']
 ['A.Not at all']
 ['A.Not at all']
 ['A.Not at all']
 ['A.Not at all']
 ['E.Extremely']
 ['A.Not at all']
 ['B.Slightly']
 ['B.Slightly']
 ['A.Not at all']
 ['E.Extremely']
 ['A.Not at all']
 ['A.Not at all']
 ['A.Not at all']
 ['B.Slightly']
 ['B.Slightly']
 ['B.Slightly']
 ['A.Not at all']
 ['A.Not at all']
 ['A.Not at all']
 ['A.Not at all']
 ['A.Not at all']
 ['A.Not at all']
 ['A.Not at all']
 ['A.Not at all']
 ['B.Slightly']
 ['B.Slightly']
 ['A.Not at all']
 ['A.Not at all']
 ['A.Not at all']
 ['C.Moderately']
 ['A.Not at all']
 ['A.Not at all']
 ['B.Slightly']
 ['A.Not at all']
 ['A.Not at all']
 ['A.Not at all']
 ['A.Not at all']
 ['A.Not at all']
 ['E.Extremely']
 ['A.Not at all']
 ['A.Not at all']
 ['A.Not at all']
 ['A.Not at all']
 ['A.Not at all']
 ['A.Not at all']
 ['A.Not at all']
 ['A.Not at all']
 ['A.Not at all']
 ['A.Not at all']
 ['A.Not at all']
 ['A.Not at all']
 ['A.Not at all']
 ['A.Not at all']
 ['A.Not at all']
 ['A.Not at all']
 ['A.Not at all']
 ['A.Not at all']
 ['A.Not at all']
 ['A.Not at all']
 ['C.Moderately']
 ['A.Not at all']
 ['A.Not at all']
 ['B.Slightly']
 ['A.Not at all']
 ['A.Not at all']
 ['A.Not at all']
 ['A.Not at all']
 ['A.Not at all']
 ['A.Not at all']
 ['A.Not at all']
 ['A.Not at all']
 ['D.Very']
 ['E.Extremely']
 ['A.Not at all']
 ['A.Not at all']
 ['A.Not at all']
 ['A.Not at all']
 ['B.Slightly']
 ['A.Not at all']
 ['B.Slightly']
 ['A.Not at all']
 ['C.Moderately']
 ['A.Not at all']
 ['A.Not at all']
 ['A.Not at all']
 ['A.Not at all']
 ['A.Not at all']
 ['B.Slightly']
 ['B.Slightly']
 ['B.Slightly']
 ['B.Slightly']
 ['C.Moderately']
 ['A.Not at all']
 ['A.Not at all']
 ['D.Very']
 ['C.Moderately']
 ['B.Slightly']
 ['A.Not at all']
 ['A.Not at all']
 ['B.Slightly']
 ['A.Not at all']
 ['A.Not at all']
 ['A.Not at all']
 ['B.Slightly']
 ['A.Not at all']
 ['A.Not at all']
 ['A.Not at all']
 ['A.Not at all']
 ['D.Very']
 ['A.Not at all']
 ['A.Not at all']
 ['A.Not at all']
 ['B.Slightly']
 ['A.Not at all']
 ['B.Slightly']
 ['B.Slightly']
 ['A.Not at all']
 ['B.Slightly']
 ['A.Not at all']
 ['A.Not at all']
 ['A.Not at all']
 ['A.Not at all']
 ['A.Not at all']
 ['D.Very']
 ['A.Not at all']
 ['A.Not at all']
 ['A.Not at all']
 ['B.Slightly']
 ['A.Not at all']
 ['A.Not at all']
 ['A.Not at all']
 ['A.Not at all']
 ['C.Moderately']
 ['B.Slightly']
 ['A.Not at all']
 ['A.Not at all']
 ['A.Not at all']
 ['D.Very']
 ['A.Not at all']
 ['B.Slightly']
 ['A.Not at all']
 ['B.Slightly']
 ['B.Slightly']
 ['A.Not at all']
 ['A.Not at all']
 ['A.Not at all']
 ['A.Not at all']
 ['E.Extremely']
 ['A.Not at all']
 ['A.Not at all']
 ['A.Not at all']
 ['D.Very']
 ['A.Not at all']
 ['A.Not at all']
 ['A.Not at all']
 ['B.Slightly']
 ['A.Not at all']
 ['A.Not at all']
 ['E.Extremely']
 ['A.Not at all']
 ['A.Not at all']
 ['A.Not at all']
 ['A.Not at all']
 ['A.Not at all']
 ['B.Slightly']
 ['A.Not at all']
 ['A.Not at all']
 ['A.Not at all']
 ['A.Not at all']
 ['C.Moderately']
 ['A.Not at all']
 ['A.Not at all']
 ['A.Not at all']
 ['A.Not at all']
 ['A.Not at all']
 ['A.Not at all']
 ['B.Slightly']
 ['A.Not at all']
 ['A.Not at all']
 ['A.Not at all']
 ['A.Not at all']
 ['A.Not at all']
 ['E.Extremely']
 ['B.Slightly']
 ['B.Slightly']
 ['A.Not at all']
 ['B.Slightly']
 ['A.Not at all']
 ['A.Not at all']
 ['A.Not at all']
 ['A.Not at all']
 ['D.Very']
 ['B.Slightly']
 ['A.Not at all']
 ['A.Not at all']
 ['A.Not at all']
 ['A.Not at all']
 ['A.Not at all']
 ['A.Not at all']
 ['A.Not at all']
 ['B.Slightly']
 ['C.Moderately']
 ['A.Not at all']
 ['C.Moderately']
 ['A.Not at all']
 ['A.Not at all']
 ['A.Not at all']
 ['A.Not at all']
 ['B.Slightly']
 ['A.Not at all']
 ['A.Not at all']
 ['A.Not at all']
 ['A.Not at all']
 ['B.Slightly']
 ['B.Slightly']
 ['C.Moderately']
 ['A.Not at all']
 ['A.Not at all']
 ['A.Not at all']
 ['A.Not at all']
 ['A.Not at all']
 ['A.Not at all']
 ['A.Not at all']
 ['A.Not at all']
 ['A.Not at all']
 ['A.Not at all']
 ['A.Not at all']
 ['B.Slightly']
 ['A.Not at all']
 ['A.Not at all']
 ['B.Slightly']
 ['A.Not at all']
 ['B.Slightly']
 ['A.Not at all']
 ['A.Not at all']
 ['A.Not at all']
 ['A.Not at all']
 ['A.Not at all']
 ['A.Not at all']
 ['A.Not at all']
 ['A.Not at all']
 ['A.Not at all']
 ['A.Not at all']
 ['C.Moderately']
 ['A.Not at all']
 ['A.Not at all']
 ['A.Not at all']
 ['A.Not at all']
 ['B.Slightly']
 ['C.Moderately']
 ['D.Very']
 ['A.Not at all']
 ['B.Slightly']
 ['A.Not at all']
 ['B.Slightly']
 ['B.Slightly']
 ['A.Not at all']
 ['B.Slightly']
 ['C.Moderately']
 ['A.Not at all']
 ['A.Not at all']
 ['B.Slightly']
 ['B.Slightly']
 ['A.Not at all']
 ['A.Not at all']
 ['A.Not at all']
 ['A.Not at all']
 ['A.Not at all']
 ['B.Slightly']
 ['A.Not at all']
 ['B.Slightly']
 ['A.Not at all']
 ['A.Not at all']
 ['A.Not at all']
 ['B.Slightly']
 ['B.Slightly']
 ['A.Not at all']
 ['B.Slightly']
 ['B.Slightly']
 ['C.Moderately']
 ['A.Not at all']
 ['A.Not at all']
 ['A.Not at all']
 ['A.Not at all']
 ['A.Not at all']
 ['A.Not at all']
 ['A.Not at all']
 ['D.Very']
 ['A.Not at all']
 ['A.Not at all']
 ['A.Not at all']
 ['A.Not at all']
 ['A.Not at all']
 ['A.Not at all']
 ['A.Not at all']
 ['A.Not at all']
 ['A.Not at all']
 ['D.Very']
 ['B.Slightly']
 ['A.Not at all']
 ['A.Not at all']
 ['A.Not at all']
 ['C.Moderately']
 ['B.Slightly']
 ['B.Slightly']
 ['A.Not at all']
 ['A.Not at all']
 ['A.Not at all']
 ['B.Slightly']
 ['A.Not at all']
 ['B.Slightly']
 ['A.Not at all']
 ['A.Not at all']
 ['A.Not at all']
 ['A.Not at all']
 ['A.Not at all']
 ['D.Very']
 ['C.Moderately']
 ['A.Not at all']
 ['C.Moderately']
 ['A.Not at all']
 ['A.Not at all']
 ['E.Extremely']
 ['A.Not at all']
 ['A.Not at all']
 ['A.Not at all']
 ['B.Slightly']
 ['A.Not at all']
 ['A.Not at all']
 ['A.Not at all']
 ['A.Not at all']
 ['A.Not at all']
 ['A.Not at all']
 ['A.Not at all']
 ['A.Not at all']
 ['E.Extremely']
 ['A.Not at all']
 ['B.Slightly']
 ['A.Not at all']
 ['E.Extremely']
 ['C.Moderately']
 ['A.Not at all']
 ['A.Not at all']
 ['B.Slightly']
 ['B.Slightly']
 ['A.Not at all']
 ['B.Slightly']
 ['B.Slightly']
 ['A.Not at all']
 ['C.Moderately']
 ['A.Not at all']
 ['A.Not at all']
 ['B.Slightly']
 ['B.Slightly']
 ['C.Moderately']
 ['A.Not at all']
 ['A.Not at all']
 ['B.Slightly']
 ['A.Not at all']
 ['A.Not at all']
 ['A.Not at all']
 ['A.Not at all']
 ['A.Not at all']
 ['B.Slightly']
 ['B.Slightly']
 ['A.Not at all']
 ['A.Not at all']
 ['A.Not at all']
 ['A.Not at all']
 ['A.Not at all']
 ['B.Slightly']
 ['A.Not at all']
 ['A.Not at all']
 ['A.Not at all']
 ['A.Not at all']
 ['A.Not at all']
 ['A.Not at all']
 ['E.Extremely']
 ['A.Not at all']
 ['A.Not at all']
 ['A.Not at all']
 ['B.Slightly']
 ['C.Moderately']
 ['A.Not at all']
 ['A.Not at all']
 ['A.Not at all']
 ['A.Not at all']
 ['A.Not at all']
 ['A.Not at all']
 ['A.Not at all']
 ['A.Not at all']
 ['B.Slightly']
 ['A.Not at all']
 ['A.Not at all']
 ['A.Not at all']
 ['A.Not at all']
 ['A.Not at all']
 ['A.Not at all']
 ['A.Not at all']
 ['A.Not at all']
 ['C.Moderately']]

In [15]:
print(X.shape)
print(y.shape)

(452, 51)
(452, 1)

In [16]:
from sklearn.preprocessing import LabelEncoder

# Step 1: Label-encode data set
label_encoder = LabelEncoder()

label_encoder.fit(y)
encoded_y = label_encoder.transform(y)

print(encoded_y)

[0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 1 0 4 2 0 0 0 0 0 0 1
 0 0 1 0 0 0 1 0 1 0 2 1 3 0 0 0 0 0 4 0 1 1 0 4 0 0 0 1 1 1 0 0 0 0 0 0 0
 0 1 1 0 0 0 2 0 0 1 0 0 0 0 0 4 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2
 0 0 1 0 0 0 0 0 0 0 0 3 4 0 0 0 0 1 0 1 0 2 0 0 0 0 0 1 1 1 1 2 0 0 3 2 1
 0 0 1 0 0 0 1 0 0 0 0 3 0 0 0 1 0 1 1 0 1 0 0 0 0 0 3 0 0 0 1 0 0 0 0 2 1
 0 0 0 3 0 1 0 1 1 0 0 0 0 4 0 0 0 3 0 0 0 1 0 0 4 0 0 0 0 0 1 0 0 0 0 2 0
 0 0 0 0 0 1 0 0 0 0 0 4 1 1 0 1 0 0 0 0 3 1 0 0 0 0 0 0 0 1 2 0 2 0 0 0 0
 1 0 0 0 0 1 1 2 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 2 0
 0 0 0 1 2 3 0 1 0 1 1 0 1 2 0 0 1 1 0 0 0 0 0 1 0 1 0 0 0 1 1 0 1 1 2 0 0
 0 0 0 0 0 3 0 0 0 0 0 0 0 0 0 3 1 0 0 0 2 1 1 0 0 0 1 0 1 0 0 0 0 0 3 2 0
 2 0 0 4 0 0 0 1 0 0 0 0 0 0 0 0 4 0 1 0 4 2 0 0 1 1 0 1 1 0 2 0 0 1 1 2 0
 0 1 0 0 0 0 0 1 1 0 0 0 0 0 1 0 0 0 0 0 0 4 0 0 0 1 2 0 0 0 0 0 0 0 0 1 0
 0 0 0 0 0 0 0 2]

C:\Users\jener\Anaconda3\envs\PythonWebMongo\lib\site-packages\sklearn\preprocessing\label.py:219: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\jener\Anaconda3\envs\PythonWebMongo\lib\site-packages\sklearn\preprocessing\label.py:252: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [17]:
for label, original_class in zip(encoded_y, y):
    print('Original Class: ' + str(original_class))
    print('Encoded Label: ' + str(label))
    print('-' * 12)

Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['B.Slightly']
Encoded Label: 1
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['B.Slightly']
Encoded Label: 1
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['B.Slightly']
Encoded Label: 1
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['B.Slightly']
Encoded Label: 1
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['E.Extremely']
Encoded Label: 4
------------
Original Class: ['C.Moderately']
Encoded Label: 2
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['B.Slightly']
Encoded Label: 1
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['B.Slightly']
Encoded Label: 1
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['B.Slightly']
Encoded Label: 1
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['B.Slightly']
Encoded Label: 1
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['C.Moderately']
Encoded Label: 2
------------
Original Class: ['B.Slightly']
Encoded Label: 1
------------
Original Class: ['D.Very']
Encoded Label: 3
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['E.Extremely']
Encoded Label: 4
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['B.Slightly']
Encoded Label: 1
------------
Original Class: ['B.Slightly']
Encoded Label: 1
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['E.Extremely']
Encoded Label: 4
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['B.Slightly']
Encoded Label: 1
------------
Original Class: ['B.Slightly']
Encoded Label: 1
------------
Original Class: ['B.Slightly']
Encoded Label: 1
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['B.Slightly']
Encoded Label: 1
------------
Original Class: ['B.Slightly']
Encoded Label: 1
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['C.Moderately']
Encoded Label: 2
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['B.Slightly']
Encoded Label: 1
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['E.Extremely']
Encoded Label: 4
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['C.Moderately']
Encoded Label: 2
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['B.Slightly']
Encoded Label: 1
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['D.Very']
Encoded Label: 3
------------
Original Class: ['E.Extremely']
Encoded Label: 4
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['B.Slightly']
Encoded Label: 1
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['B.Slightly']
Encoded Label: 1
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['C.Moderately']
Encoded Label: 2
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['B.Slightly']
Encoded Label: 1
------------
Original Class: ['B.Slightly']
Encoded Label: 1
------------
Original Class: ['B.Slightly']
Encoded Label: 1
------------
Original Class: ['B.Slightly']
Encoded Label: 1
------------
Original Class: ['C.Moderately']
Encoded Label: 2
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['D.Very']
Encoded Label: 3
------------
Original Class: ['C.Moderately']
Encoded Label: 2
------------
Original Class: ['B.Slightly']
Encoded Label: 1
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['B.Slightly']
Encoded Label: 1
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['B.Slightly']
Encoded Label: 1
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['D.Very']
Encoded Label: 3
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['B.Slightly']
Encoded Label: 1
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['B.Slightly']
Encoded Label: 1
------------
Original Class: ['B.Slightly']
Encoded Label: 1
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['B.Slightly']
Encoded Label: 1
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['D.Very']
Encoded Label: 3
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['B.Slightly']
Encoded Label: 1
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['C.Moderately']
Encoded Label: 2
------------
Original Class: ['B.Slightly']
Encoded Label: 1
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['D.Very']
Encoded Label: 3
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['B.Slightly']
Encoded Label: 1
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['B.Slightly']
Encoded Label: 1
------------
Original Class: ['B.Slightly']
Encoded Label: 1
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['E.Extremely']
Encoded Label: 4
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['D.Very']
Encoded Label: 3
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['B.Slightly']
Encoded Label: 1
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['E.Extremely']
Encoded Label: 4
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['B.Slightly']
Encoded Label: 1
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['C.Moderately']
Encoded Label: 2
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['B.Slightly']
Encoded Label: 1
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['E.Extremely']
Encoded Label: 4
------------
Original Class: ['B.Slightly']
Encoded Label: 1
------------
Original Class: ['B.Slightly']
Encoded Label: 1
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['B.Slightly']
Encoded Label: 1
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['D.Very']
Encoded Label: 3
------------
Original Class: ['B.Slightly']
Encoded Label: 1
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['B.Slightly']
Encoded Label: 1
------------
Original Class: ['C.Moderately']
Encoded Label: 2
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['C.Moderately']
Encoded Label: 2
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['B.Slightly']
Encoded Label: 1
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['B.Slightly']
Encoded Label: 1
------------
Original Class: ['B.Slightly']
Encoded Label: 1
------------
Original Class: ['C.Moderately']
Encoded Label: 2
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['B.Slightly']
Encoded Label: 1
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['B.Slightly']
Encoded Label: 1
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['B.Slightly']
Encoded Label: 1
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['C.Moderately']
Encoded Label: 2
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['B.Slightly']
Encoded Label: 1
------------
Original Class: ['C.Moderately']
Encoded Label: 2
------------
Original Class: ['D.Very']
Encoded Label: 3

------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['B.Slightly']
Encoded Label: 1
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['B.Slightly']
Encoded Label: 1
------------
Original Class: ['B.Slightly']
Encoded Label: 1
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['B.Slightly']
Encoded Label: 1
------------
Original Class: ['C.Moderately']
Encoded Label: 2
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['B.Slightly']
Encoded Label: 1
------------
Original Class: ['B.Slightly']
Encoded Label: 1
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['B.Slightly']
Encoded Label: 1
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['B.Slightly']
Encoded Label: 1
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['B.Slightly']
Encoded Label: 1
------------
Original Class: ['B.Slightly']
Encoded Label: 1
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['B.Slightly']
Encoded Label: 1
------------
Original Class: ['B.Slightly']
Encoded Label: 1
------------
Original Class: ['C.Moderately']
Encoded Label: 2
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['D.Very']
Encoded Label: 3
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['D.Very']
Encoded Label: 3
------------
Original Class: ['B.Slightly']
Encoded Label: 1
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['C.Moderately']
Encoded Label: 2
------------
Original Class: ['B.Slightly']
Encoded Label: 1
------------
Original Class: ['B.Slightly']
Encoded Label: 1
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['B.Slightly']
Encoded Label: 1
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['B.Slightly']
Encoded Label: 1
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['D.Very']
Encoded Label: 3
------------
Original Class: ['C.Moderately']
Encoded Label: 2
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['C.Moderately']
Encoded Label: 2
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['E.Extremely']
Encoded Label: 4
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['B.Slightly']
Encoded Label: 1
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['E.Extremely']
Encoded Label: 4
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['B.Slightly']
Encoded Label: 1
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['E.Extremely']
Encoded Label: 4
------------
Original Class: ['C.Moderately']
Encoded Label: 2
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['B.Slightly']
Encoded Label: 1
------------
Original Class: ['B.Slightly']
Encoded Label: 1
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['B.Slightly']
Encoded Label: 1
------------
Original Class: ['B.Slightly']
Encoded Label: 1
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['C.Moderately']
Encoded Label: 2
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['B.Slightly']
Encoded Label: 1
------------
Original Class: ['B.Slightly']
Encoded Label: 1
------------
Original Class: ['C.Moderately']
Encoded Label: 2
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['B.Slightly']
Encoded Label: 1
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['B.Slightly']
Encoded Label: 1
------------
Original Class: ['B.Slightly']
Encoded Label: 1
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['B.Slightly']
Encoded Label: 1
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['E.Extremely']
Encoded Label: 4
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['B.Slightly']
Encoded Label: 1
------------
Original Class: ['C.Moderately']
Encoded Label: 2
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['B.Slightly']
Encoded Label: 1
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['C.Moderately']
Encoded Label: 2
------------

In [18]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, encoded_y, random_state=5)

## Data Preprocessing ##

In [19]:
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
X_scaler = StandardScaler().fit(X_train)

In [20]:
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [21]:
from keras.utils import to_categorical

# One-hot encoding
y_train_categorical = to_categorical(y_train)
y_test_categorical = to_categorical(y_test)

Using TensorFlow backend.

## Create Deep Learning Model ##

In [22]:
from tensorflow.keras.models import Sequential

model = Sequential()

In [23]:
from tensorflow.keras.layers import Dense
number_inputs = 51

number_hidden_nodes = 156
model.add(Dense(units=number_hidden_nodes,
                activation='relu', input_dim=number_inputs))

WARNING:tensorflow:From C:\Users\jener\Anaconda3\envs\PythonWebMongo\lib\site-packages\tensorflow\python\ops\init_ops.py:1251: calling VarianceScaling.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor

In [24]:
# add another layer??
number_layer_classes = 10
model.add(Dense(units=number_layer_classes, activation='relu'))
model.add(Dense(units=number_layer_classes, activation='relu'))
# model.add(Dense(units=number_layer_classes, activation='relu'))
# model.add(Dense(units=number_layer_classes, activation='relu'))
# model.add(Dense(units=number_layer_classes, activation='relu'))

In [25]:
# add another layer??
number_classes = 5
model.add(Dense(units=number_classes, activation='softmax'))

In [26]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense (Dense)                (None, 150)               7800
_________________________________________________________________
dense_1 (Dense)              (None, 10)                1510
_________________________________________________________________
dense_2 (Dense)              (None, 10)                110
_________________________________________________________________
dense_3 (Dense)              (None, 10)                110
_________________________________________________________________
dense_4 (Dense)              (None, 5)                 55
=================================================================
Total params: 9,585
Trainable params: 9,585
Non-trainable params: 0
_________________________________________________________________

In [27]:
# Use categorical crossentropy for categorical data and mean squared error for regression
# Hint: your output layer in this example is using software for logistic regression (categorical)
# If your output layer activation was `linear` then you may want to use `mse` for loss
model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

In [28]:
# Fit (train) the model
model.fit(
    X_train_scaled,
    y_train_categorical,
    epochs=50,
    shuffle=True,
    verbose=2
)

Epoch 1/50
339/339 - 0s - loss: 1.5480 - acc: 0.4956
Epoch 2/50
339/339 - 0s - loss: 1.3873 - acc: 0.7109
Epoch 3/50
339/339 - 0s - loss: 1.2189 - acc: 0.7168
Epoch 4/50
339/339 - 0s - loss: 1.0476 - acc: 0.7139
Epoch 5/50
339/339 - 0s - loss: 0.9076 - acc: 0.7139
Epoch 6/50
339/339 - 0s - loss: 0.8160 - acc: 0.7168
Epoch 7/50
339/339 - 0s - loss: 0.7464 - acc: 0.7286
Epoch 8/50
339/339 - 0s - loss: 0.6998 - acc: 0.7345
Epoch 9/50
339/339 - 0s - loss: 0.6616 - acc: 0.7345
Epoch 10/50
339/339 - 0s - loss: 0.6254 - acc: 0.7375
Epoch 11/50
339/339 - 0s - loss: 0.5963 - acc: 0.7522
Epoch 12/50
339/339 - 0s - loss: 0.5681 - acc: 0.7729
Epoch 13/50
339/339 - 0s - loss: 0.5373 - acc: 0.7906
Epoch 14/50
339/339 - 0s - loss: 0.5092 - acc: 0.7935
Epoch 15/50
339/339 - 0s - loss: 0.4823 - acc: 0.8083
Epoch 16/50
339/339 - 0s - loss: 0.4574 - acc: 0.8142
Epoch 17/50
339/339 - 0s - loss: 0.4343 - acc: 0.8260
Epoch 18/50
339/339 - 0s - loss: 0.4140 - acc: 0.8260
Epoch 19/50
339/339 - 0s - loss: 0.3934 - acc: 0.8289
Epoch 20/50
339/339 - 0s - loss: 0.3738 - acc: 0.8319
Epoch 21/50
339/339 - 0s - loss: 0.3565 - acc: 0.8466
Epoch 22/50
339/339 - 0s - loss: 0.3340 - acc: 0.8496
Epoch 23/50
339/339 - 0s - loss: 0.3183 - acc: 0.8614
Epoch 24/50
339/339 - 0s - loss: 0.3010 - acc: 0.8614
Epoch 25/50
339/339 - 0s - loss: 0.2862 - acc: 0.8702
Epoch 26/50
339/339 - 0s - loss: 0.2705 - acc: 0.8850
Epoch 27/50
339/339 - 0s - loss: 0.2579 - acc: 0.8879
Epoch 28/50
339/339 - 0s - loss: 0.2456 - acc: 0.8938
Epoch 29/50
339/339 - 0s - loss: 0.2348 - acc: 0.8909
Epoch 30/50
339/339 - 0s - loss: 0.2229 - acc: 0.9027
Epoch 31/50
339/339 - 0s - loss: 0.2099 - acc: 0.9086
Epoch 32/50
339/339 - 0s - loss: 0.2000 - acc: 0.9233
Epoch 33/50
339/339 - 0s - loss: 0.1899 - acc: 0.9292
Epoch 34/50
339/339 - 0s - loss: 0.1826 - acc: 0.9351
Epoch 35/50
339/339 - 0s - loss: 0.1751 - acc: 0.9351
Epoch 36/50
339/339 - 0s - loss: 0.1673 - acc: 0.9351
Epoch 37/50
339/339 - 0s - loss: 0.1599 - acc: 0.9351
Epoch 38/50
339/339 - 0s - loss: 0.1517 - acc: 0.9351
Epoch 39/50
339/339 - 0s - loss: 0.1433 - acc: 0.9410
Epoch 40/50
339/339 - 0s - loss: 0.1353 - acc: 0.9528
Epoch 41/50
339/339 - 0s - loss: 0.1294 - acc: 0.9528
Epoch 42/50
339/339 - 0s - loss: 0.1235 - acc: 0.9587
Epoch 43/50
339/339 - 0s - loss: 0.1175 - acc: 0.9587
Epoch 44/50
339/339 - 0s - loss: 0.1124 - acc: 0.9617
Epoch 45/50
339/339 - 0s - loss: 0.1058 - acc: 0.9617
Epoch 46/50
339/339 - 0s - loss: 0.1014 - acc: 0.9705
Epoch 47/50
339/339 - 0s - loss: 0.0960 - acc: 0.9705
Epoch 48/50
339/339 - 0s - loss: 0.0895 - acc: 0.9705
Epoch 49/50
339/339 - 0s - loss: 0.0836 - acc: 0.9705
Epoch 50/50
339/339 - 0s - loss: 0.0798 - acc: 0.9705

## Quantify Trained Model ##

In [29]:
model_loss, model_accuracy = model.evaluate(
    X_test_scaled, y_test_categorical, verbose=2)
print(
    f"Normal Neural Network - Loss: {model_loss}, Accuracy: {model_accuracy}")

113/113 - 0s - loss: 2.1343 - acc: 0.5575
Normal Neural Network - Loss: 2.1343025718115074, Accuracy: 0.5575221180915833

## Save Trained Model ##

In [30]:
# Save the model
# model.save("students_deep_learning_trained.h5")

In [31]:
# import numpy as np
# predict_student = encoded_students_df.iloc[4]

# predict_student = np.expand_dims(predict_student, axis=0)

# model.predict_classes(predict_student)
# # predict

In [32]:
data = {'Deep Learning (Rural) Accuracy': [model_accuracy]}
df = pd.DataFrame(data=data)
df

   Deep Learning (Rural) Accuracy
0                        0.557522